CREATE DATABASE CATALOGO;
GO

USE CATALOGO;
GO

CREATE TABLE Genero(
	IdGenero TINYINT PRIMARY KEY IDENTITY (1,1),
	NomeGenero VARCHAR(30)
);
GO

CREATE TABLE Filme(
	IdFilme SMALLYNG PRIMARY KEY IDENTITY (1,1),
	IdGenero TINYINT FOREIGN KEY REFERENCES Genero(IdGenero),
	TituloFilme VARCHAR(70)
);

