CREATE DATABASE Unidas;
GO

USE Unidas;
GO

CREATE TABLE Pessoa(
	IdPessoa INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(20) NOT NULL
);
GO

CREATE TABLE CNH(
	IdCNH INT PRIMARY KEY IDENTITY(1,1),
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa),
	Descricao VARCHAR(11) NOT NULL UNIQUE
);
GO

CREATE TABLE Telefone(
	IdTelefone INT PRIMARY KEY IDENTITY(1,1),
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa),
	NumeroTelefone CHAR(13) NOT NULL
);
GO

CREATE TABLE Email(
	IdEmail INT PRIMARY KEY IDENTITY(1,1),
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa),
	EnderecoEmail VARCHAR(256) NOT NULL UNIQUE
);
GO