CREATE DATABASE Pclinics;
GO

USE Pclinics;
GO

CREATE TABLE Clinica(
	IdClinica INT PRIMARY KEY IDENTITY(1,1),
	NomeClinica VARCHAR(20) NOT NULL,
	Endereco VARCHAR(100) NOT NULL UNIQUE
);
GO

CREATE TABLE Veterinario(
	IdVeterinario INT PRIMARY KEY IDENTITY(1,1),
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
	NomeVeterinario VARCHAR(20)
);
GO

CREATE TABLE Dono(
	IdDono INT PRIMARY KEY IDENTITY(1,1),
	NomeDono VARCHAR(20)
);
GO

CREATE TABLE TipoPet(
	IdTipoPet INT PRIMARY KEY IDENTITY(1,1),
	NomeTipoPet VARCHAR(20)
);
GO

CREATE TABLE Raca(
	IdRaca INT PRIMARY KEY IDENTITY(1,1),
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet),
	NomeRaca VARCHAR(30)
);
GO

CREATE TABLE Pet(
	IdPet INT PRIMARY KEY IDENTITY(1,1),
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
	NomePet VARCHAR(20),
	DataNascimento DATE
);
GO

CREATE TABLE Consulta(
	IdConsulta INT PRIMARY KEY IDENTITY(1,1),
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet),
	DataConsulta SMALLDATETIME,
	DescricaoConsulta VARCHAR(2000)
);
GO